---
- include: create.yml

- name: configure and deploy the webserver
  hosts: www
  roles:
    - common
    - ruby19
    - passenger
    - nginx

- name: configure and deploy the db server
  hosts: db
  roles:
    - common
    - mysql