---
- include: create.yml

- name: configure and deploy the webserver
  hosts: webservers
  roles:
    - common
    - ruby19
    - passenger
    - nginx

- name: configure and deploy the db server
  hosts: dbservers
  roles:
    - common
    - mysql