- name: ensure mysql is installed
  remote_user: vagrant
  sudo: true
  apt: pkg=mysql-server state=present update_cache=yes

- name: ensure mysql is running
  remote_user: vagrant
  sudo: true
  service: name=mysql state=started enabled=true
