- name: ensure mysql is installed
  apt: pkg=mysql-server state=present update_cache=yes

- name: ensure mysql is running
  service: name=mysql state=started enabled=true

#- name: insert iptables rule
#  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables

- name: ensure python-mysqldb is installed
  apt: pkg=python-mysqldb state=latest update_cache=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
