---
- name: example ec2 group
  local_action:
    module: ec2_group
    name: webservers
    description: an example EC2 group
    region: us-east-1
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- include: ../../../tasks/launch_ec2_instance.yml instance_id=i-test keypair=test security_group=webservers instance_tags={{ instance_tags }} host_groupname=webservers
