- name: ensure the app user exists
  remote_user: vagrant
  sudo: true
  user: name={{ app_user }}  comment="PetShop app" uid=1040 shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: ensure curl is installed
  remote_user: vagrant
  sudo: true
  apt: pkg=curl state=present update_cache=yes

- name: ensure libcurl is installed
  remote_user: vagrant
  sudo: true
  apt: pkg=libcurl4-openssl-dev state=present

- name: Install git
  remote_user: vagrant
  sudo: true
  apt: pkg=git state=present

