---
- name: create ec2 group for dbservers
  local_action:
    module: ec2_group
    name: dbservers
    description: Opens SSH and mysql ports
    region: us-east-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0

- include: ../../../tasks/launch_ec2_instance.yml instance_id=db-{{env_name}} keypair=test security_group=dbservers instance_tags={{instance_tags}} host_groupname=db hostname=db.{{env_name}}.{{domain}}
