---
- name: example ec2 group
  local_action:
    module: ec2_group
    name: example
    description: an example EC2 group
    region: us-east-1
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Launch instance
  local_action:
    id: i-test
    module: ec2
    keypair: test
    instance_type: t1.micro
    region: us-east-1
    image: ami-93f4a8fa
    group: example
    wait: yes
  register: ec2

- name: Add new instance to host group
  local_action: add_host hostname={{ item.public_ip }} groupname=webservers ansible_ssh_user=ubuntu
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 timeout=320 state=started
  with_items: ec2.instances